services:
  - type: web
    name: uk-tamil-awards-2025
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
